/**
* @license 
* acordeones.js
*/
jQuery.noConflict(),function($){$(function(){$(".acordeon").find("h3").each(function(){$(this).nextAll().wrapAll('<div class="contenidoAcordeon"></div>'),$("<em></em>").appendTo(this)}),$(".acordeon").find("h3").on("click",function(){$(this).next("div").slideToggle(),$(this).toggleClass("abierto")}),$(".acordeon").find("h2").each(function(){$(this).nextAll().wrapAll('<div class="contenidoAcordeon"></div>'),$("<em></em>").appendTo(this)}),$(".acordeon").find("h2").on("click",function(){$(this).next("div").slideToggle(),$(this).toggleClass("abierto")}),$(".detalleAsset").find("p.tituloAcordeon").each(function(){$(this).nextUntil("p.tituloInterno").wrapAll('<div class="contenidoAcordeon"></div>'),$("<em></em>").appendTo(this)}),$(".detalleAsset").find("p.tituloAcordeon").on("click",function(){$(this).next("div").slideToggle(),$(this).toggleClass("abierto")}),$(".textoContenido").find("p.tituloAcordeon").each(function(){$(this).nextUntil("p.tituloInterno").wrapAll('<div class="contenidoAcordeon"></div>'),$("<em></em>").appendTo(this)}),$(".textoContenido").find("p.tituloAcordeon").on("click",function(){$(this).next("div").slideToggle(),$(this).toggleClass("abierto")}),$(".contenidoApartado").find("p.tituloAcordeon").each(function(){$(this).nextUntil("p.tituloInterno").wrapAll('<div class="contenidoAcordeon"></div>'),$("<em></em>").appendTo(this)}),$(".contenidoApartado").find("p.tituloAcordeon").on("click",function(){$(this).next("div").slideToggle(),$(this).toggleClass("abierto")})})}(jQuery),/**
* @license 
* tabsTexto.js
*/
jQuery.noConflict(),function($){$(function(){$(".panes").before('<ul id="etiquetas" class="tabs"></ul>'),$("#etiquetas").before($(".panes h2")),$("#etiquetas").before($(".panes > h3")),$(".panes .cajaGenerica a[name]").each(function(){var e=$(this).attr("name");$(this).parent().attr("id","tab"+e)}),$(".panes .textoContenido h3").each(function(){var e=$(this).parents(".cajaGenerica").attr("id"),i=$(this).html();$(".tabs").append('<li><a href="#'+e+'">'+i+"</a></li>")}),$(".panes .textoContenidoTab h3").each(function(){var e=$(this).parents(".cajaGenerica").attr("id"),i=$(this).html();$(".tabs").append('<li><a href="#'+e+'">'+i+"</a></li>")}),$("ul.tabs").tabs("div.panes > div")})}(jQuery),/**
* @license 
* portal30.js - dgenerico
*/
jQuery.noConflict(),function($){$(function(){$("#idiomas li:has(a)").addClass("activo"),$("#buscadorCabecera").find(".botonEnviarBuscador").attr("value",""),$(".cajaDesplegable").find("h3").nextAll().not("div").wrapAll('<div class="relacionadosItem" />'),$(".cajaDesplegable").find(".imagen").on("click",function(){$(this).next().find(".relacionadosItem").slideToggle()}),$(".cajaDesplegable").find("h3").on("click",function(){$(this).nextAll("div.relacionadosItem").slideToggle()}),$(".cajaDesplegable").find("h3").on("click",function(){$(this).nextAll("ul.listaCategorias").slideToggle()}),$(".cajaDesplegable").find("img").on("click",function(){$(this).next().find(".listadoResultados").slideToggle()}),$(".cajaDesplegable").find("h2").on("click",function(){$(this).nextAll("dl.relacionadosItem").slideToggle()}),$(".cajaDesplegable").find("img").on("click",function(){$(this).addClass("imagenDesplegable"),$(this).next("dl").slideToggle()}),$(".cajaDesplegable").find("h2").on("click",function(){$(this).nextAll("dl").addClass("dlDesplegar"),$(this).nextAll("dl").slideToggle()}),$(".cajaDesplegable").find("h3").nextAll().not("div").wrapAll('<div class="relacionadosItem" />'),$("#buscadorFormularioFechas").find("p").toggleClass("abierto"),$("#buscadorFormularioFechas").find("p").on("click",function(){$(this).next("fieldset").slideToggle(),$(this).toggleClass("abierto")}),$(".buscadorCategoriasComplejo ul.cat1nivel > li").has("ul").find("> label").addClass("padre"),$(".buscadorCategoriasComplejo ul.cat1nivel > li").has("ul").find(" label").on("click",function(){return $(this).toggleClass("abierto"),$(this).parent().children("ul").slideToggle(),!1}),$(".buscadorCategoriasComplejo").find("input").on("click",function(){$("li.catMarcada").removeClass("catMarcada"),$(this).parents("li").addClass("catMarcada")}),$("#barraCompartir").find("li.compartir > a").on("click",function(){return $(this).toggleClass("abierto"),$(this).next("ul").slideToggle(),!1}),$(".concDesplegable").find(".desConTitulo").append('<span class="fa fa-arrow-circle-o-down"></span>'),$(".concDesplegable").find("span.fa").on("click",function(){$(this).toggleClass("abierto"),$(this).prev("div").slideToggle()}),$("p.masInfo").each(function(){var e=$(this).prev();$(this).appendTo(e)}),outdatedBrowser({color:"#FFF",lowerThan:"transform",languagePath:""}),$(".mason > div").addClass("brick"),$(".mason > div:first-of-type").removeClass("brick");var e=$(".mason");e.masonry({columnWidth:".anchoBrick",gutter:1,itemSelector:".brick"});var i=e.data("masonry")})}(jQuery),/**
* @license 
* portal30mod.js
*/
Modernizr.load([{load:"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"},{test:Modernizr.mq("only all and (max-width:44.9em)"),yep:["//estaticos.coruna.es/js/menu-min.js"]},{test:Modernizr.mq("only all and (min-width:45em) and (max-width:59.9em)"),yep:["//estaticos.coruna.es/js/menuTablet-min.js"]},{test:Modernizr.mq("only all and (min-width:60em)"),yep:["//estaticos.coruna.es/js/menuGr-min.js"]}]);